project:
  type: website
  output-dir: _site

website:
  title: "Bidirectional Dijkstra Project"

format:
  revealjs:
    theme: default
    transition: slide
    slide-number: true
    html-math-method: katex
    code-line-numbers: true
    highlight-style: github