project:
  type: website

format:
  revealjs:
    theme: [default, custom.scss]
    logo: images/tau_logo.png
    slide-number: true
    show-slide-number: all
    html-math-method: katex
    chalkboard: true
    highlight-style: github