project:
  type: website

metadata:
  title: "Bidirectional Dijkstra’s Algorithm is Instance-Optimal"
  subtitle: "Haeupler, Hladík, Rozhoň, Tarjan and Tětek"
  author: "*Presenting: Saar Bar Oz, Ron Vulkan, Raz Sapir, Amitai Hazan*"

format:
  revealjs:
    theme: simple
    logo: images/tau_logo.png
    slide-number: true
    show-slide-number: all
    html-math-method: katex
    chalkboard: true
    revealjs-plugins:
      - pointer
    highlight-style: github
